### ISSUE TITLE
Will this be published on GitHub Marketplace? 

### ISSUE THREAD

**Issue by jpvalery** [CultureHQ/actions-yarn#5]
Hey there! 

Thanks for making this! It looks like the most optimized action I've seen for yarn. 
Will you be publishing it on GH Marketplace so it can be easily added to any repo? 

Thanks!

**Comment by kddnewton** [comment]
Hey @jpvalery - yeah I built this before that was a thing, so now I need to figure out how to do that. As soon as I do I'll push it out though! There's got to be some docs around here somewhere...

**Comment by kddnewton** [comment]
Published! https://github.com/marketplace/actions/yarn-cli
